### ISSUE TITLE
A link to result

### ISSUE THREAD

**Issue by dodlaz** [Niler851/studentportalen-extended#1]
A direct link to studentportal's result page on the app

**Comment by Niler851** [comment]
Sure, will do !

**Comment by Niler851** [comment]
Hmmm there are two solutions i can think of now. the one im going with ruins the startpage of studentportalen a bit. 
since the url does not update when clicking "login" but remains at https://www3.student.liu.se/portal/login
the original script was not injected. 
But now i inject it at https://www3.student.liu.se/portal/login aswell. makes it look a bit worse when one does a vanilla login. Can probably solve this a bit better in the future but this will do for now. 
A update should be comming out in a couple of hours.
